### ISSUE TITLE
Major Bug: Crash during export

### ISSUE THREAD

**Issue by TacoTheDank** [RodrigoDavy/PixelArtist#29]
```
FATAL EXCEPTION: main
Process: rodrigodavy.com.github.pixelartist, PID: 16706
android.os.FileUriExposedException: file:///storage/emulated/0/Pictures/Pixel%20Artist/IMG_201914_337496.jpg exposed beyond app through Intent.getData()
	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1978)
	at android.net.Uri.checkFileUriExposed(Uri.java:2371)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:10936)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:10887)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1667)
	at android.app.Activity.startActivityForResult(Activity.java:4688)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:657)
	at android.app.Activity.startActivityForResult(Activity.java:4646)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:644)
	at android.app.Activity.startActivity(Activity.java:5007)
	at android.app.Activity.startActivity(Activity.java:4975)
	at rodrigodavy.com.github.pixelartist.MainActivity.openScreenshot(MainActivity.java:465)
	at rodrigodavy.com.github.pixelartist.MainActivity.screenShot(MainActivity.java:448)
	at rodrigodavy.com.github.pixelartist.MainActivity$5.execute(MainActivity.java:239)
	at rodrigodavy.com.github.pixelartist.MainActivity.lambda$onCreate$0(MainActivity.java:93)
	at rodrigodavy.com.github.pixelartist.-$$Lambda$MainActivity$P2Mn_n_zDOnE_m3DBfVJSYBOqoU.onItemClick(Unknown Source:6)
	at android.widget.AdapterView.performItemClick(AdapterView.java:362)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1689)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:4130)
	at android.widget.AbsListView$7.run(AbsListView.java:6608)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:6981)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

Running Android 9.0 Pie (API 28) on a Samsung Note 9.

Video for reference: https://streamable.com/f3c0h

**Comment by RodrigoDavy** [comment]
Should be fixed now, could you confirm for me?

**Comment by TacoTheDank** [comment]
https://github.com/RodrigoDavy/PixelArtist/commit/e7e2c3e5bbd8fadda7be47ded2a8956dd43027c8
