### ISSUE TITLE
Major Bug: Crash when changing activity

### ISSUE THREAD

**Issue by TacoTheDank** [RodrigoDavy/PixelArtist#30]
```
FATAL EXCEPTION: main
Process: rodrigodavy.com.github.pixelartist, PID: 17792
java.lang.RuntimeException: Unable to stop activity {rodrigodavy.com.github.pixelartist/rodrigodavy.com.github.pixelartist.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.drawable.ColorDrawable.getColor()' on a null object reference
	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4360)
	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4330)
	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4405)
	at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:41)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:6981)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.drawable.ColorDrawable.getColor()' on a null object reference
	at rodrigodavy.com.github.pixelartist.MainActivity.saveFile(MainActivity.java:378)
	at rodrigodavy.com.github.pixelartist.MainActivity.onStop(MainActivity.java:119)
	at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1432)
	at android.app.Activity.performStop(Activity.java:7652)
	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4352)
	... 12 more
```

Running Android 9.0 Pie (API 28) on a Samsung Note 9.

Video for reference: https://streamable.com/5hps7

**Comment by RodrigoDavy** [comment]
Should be fixed now, could you confirm for me?

**Comment by TacoTheDank** [comment]
https://github.com/RodrigoDavy/PixelArtist/commit/65e4a14ece81f5dd97700495a1e85faf09536d6d
