### ISSUE TITLE
Major Bug: Crash when hitting save

### ISSUE THREAD

**Issue by TacoTheDank** [RodrigoDavy/PixelArtist#32]
```
FATAL EXCEPTION: main
Process: rodrigodavy.com.github.pixelartist, PID: 18347
java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.view.View.getBackground()' on a null object reference
	at rodrigodavy.com.github.pixelartist.MainActivity.saveFile(MainActivity.java:378)
	at rodrigodavy.com.github.pixelartist.MainActivity$4.lambda$execute$0(MainActivity.java:216)
	at rodrigodavy.com.github.pixelartist.-$$Lambda$MainActivity$4$Zt-n2WSLyBT4r5AKmZAaXCSCEsM.onClick(Unknown Source:4)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:6981)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

**Comment by RodrigoDavy** [comment]
Should be fixed now, could you confirm?

**Comment by TacoTheDank** [comment]
https://github.com/RodrigoDavy/PixelArtist/commit/65e4a14ece81f5dd97700495a1e85faf09536d6d
